# MyAspNetCoreApp
#Imagen Base para Producción
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

#Imagen Base para Construcción
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY *.csproj .
RUN dotnet restore 

#Construcción de la Aplicación
COPY . .
WORKDIR "/src/."
RUN dotnet build  -c Release -o /app/build

#Publicación de la Aplicación
FROM build AS publish
RUN dotnet publish -c Release -o /app/publish

#Construcción de la Imagen Final
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MyAspNetCoreApp.dll"]
